services:
  proxy:
    image: nginx:1.25-alpine
    container_name: proxy
    hostname: proxy
    restart: unless-stopped
    env_file: ./.docker/proxy/.env
    ports:
      - '80:80'
    volumes:
      - './.docker/proxy/templates:/etc/nginx/templates'
      - './.docker/proxy/certs:/etc/ssl/certs'
      - './.docker/proxy/private:/etc/ssl/private'
    depends_on:
      - blog

  blog:
    image: vorant94/digital-garden-blog:2.0.0
    #    build:
    #      dockerfile: ./packages/blog/Dockerfile
    container_name: blog
    hostname: blog
    restart: unless-stopped
    env_file: ./packages/blog/.env
