services:
  blog:
    build:
      dockerfile: ./packages/blog/Dockerfile
    container_name: blog
    hostname: blog
    restart: unless-stopped
    env_file: ./packages/blog/.env
    ports:
      - "3000:3000"
