app = 'digital-garden-blog'
primary_region = 'waw'

[build]
  dockerfile = "./packages/blog/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = 3000
  BASE_URL = "https://www.vorant94.io"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
