name: CI/CD

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ['master']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn workspaces focus @digital-garden/blog

      - run: cd packages/blog

      - run: yarn vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - run: yarn vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - run: yarn vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
