name: CI/CD

on: push

jobs:
  format-build-test-and-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --ignore-scripts --no-audit

      - run: npm run format:check

      - run: npm run build:client --workspace=@digital-garden/blog

      - run: npm run build:server --workspace=@digital-garden/blog

      - run: npm run test --workspace=@digital-garden/blog

      - run: npm run e2e:setup --workspace=@digital-garden/blog -- --with-deps

      - run: npm run e2e --workspace=@digital-garden/blog

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./packages/blog/playwright-report/
          retention-days: 30

  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
