name: CI/CD

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  BASE_URL: ${{ vars.BASE_URL }}

on: push

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn

      - run: yarn workspace @digital-garden/blog run check

      - run: yarn test

      - run: yarn workspace @digital-garden/blog run e2e:setup --with-deps

      - run: yarn workspace @digital-garden/blog run e2e

      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./packages/blog/playwright-report/
          retention-days: 30

      - run: yarn build
        if: github.ref != 'refs/heads/master'

  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn

      - run: yarn workspace @digital-garden/blog run vercel:pull --token=${{ secrets.VERCEL_TOKEN }}

      - run: yarn workspace @digital-garden/blog run vercel:build --token=${{ secrets.VERCEL_TOKEN }}

      - run: yarn workspace @digital-garden/blog run vercel:deploy --token=${{ secrets.VERCEL_TOKEN }}
