name: CI/CD

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - run: npm ci

      - run: npm run check

      - run: npm run build

      - uses: actions/upload-pages-artifact@v1.0.4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/deploy-pages@v1
